name: CI
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Lighthouse Audit
        uses: jakejarvis/lighthouse-action@master
        with:
          url: 'https://womeninsoftware.jp/'
      - uses: actions/upload-artifact@master
        with:
          name: report
          path: './report'